name: Build & Push (Docker Hub)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: udiecynthia
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push (root context)
        uses: docker/build-push-action@v6
        with:
          context: ./hospital-api
          push: true
          tags: udiecynthia/hospital-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

